dist: xenial
language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: XQQaUPMOHURNW6DSPYFwtzTjCDP5QQIfXXYv6ufbGF1l070ierTsc0XLSGZyFM5ghA5cuALcxJptf2dxB9QoBInmKFbkqCSmpcnLzd4MTxS4OP05ejK/7Y7UcEAGYozeuyNONhP+X8dgKXu1dXWqn/0lFppUC0kgWjypNrBe+uDU9zlgd/IQlzh5kf7K2SGN1re+NdB9TMsfjbNnwOXKydWbPJ+n3u8biVH3u0EnndIGWeQfvLzNejcBZoGhB5lFwitHTQyQTPBjF/QELMMyhUlWyULa6TbjzqAYNHqq5DyQLP6XrQkzLmER5kMkET4jfsCy0RQwpm64SU/yYWZnQBbnmsLwgCJMbUIQvAIeksVMscs7aqerPXr3cjnTtKXaBaPb4gnyry6x20pimnSGTKrLmMOGjq/IeQuWmGASloJFyO5+OshkLcTKB4cngxfGoYhIHsX/Dfr/do/3W3hIH2J3Y4Qb81cy4te8DCHIEuPTo19KzLRz16Sv0lkMzWNjQbDAgArcAht4VVQRXTNbBQfaQMUFsBl36BvtXx8wT2ZjpPkYeO/gSegZ3Y6ryTrWBy9rj+IP3i986Kg8PC2gHP8gQnOPmRxTd0wdmUbj+iDzWQ9d/Iqayrk6R/McWBbOD2h0Jtkwc+CfOdm+nxZe1nfMPW22toxGcCw8m9cuLPg=
  on: master
  app: everycors
run:
- npm run build
cache:
  directories:
  - "~/.npm"
notifications:
  email: true
